dependencies:
- annexremote==1.6.0
- asttokens==2.0.8
- attrs==22.1.0
- backcall==0.2.0
- boto==2.49.0
- certifi==2022.12.7
- cffi==1.15.1
- chardet==5.1.0
- charset-normalizer==3.1.0
- cloudpickle==2.2.1
- contourpy==1.0.5
- cryptography==39.0.2
- cycler==0.11.0
- datalad==0.18.2
- debugpy==1.6.3
- decorator==5.1.1
- distro==1.8.0
- entrypoints==0.4
- et-xmlfile==1.1.0
- executing==1.0.0
- fasteners==0.18
- fonttools==4.37.3
- future==0.18.2
- h5py==3.7.0
- humanize==4.6.0
- idna==3.4
- importlib-metadata==6.0.0
- importlib-resources==6.4.5
- ipykernel==6.15.3
- ipython==8.5.0
- iso8601==1.1.0
- jaraco.classes==3.2.3
- jedi==0.18.1
- jeepney==0.8.0
- joblib==1.2.0
- jsonschema==4.16.0
- jupyter-client==7.3.5
- jupyter-core==4.11.1
- keyring==23.13.1
- keyrings.alt==4.2.0
- kiwisolver==1.4.4
- llvmlite==0.40.1
- looseversion==1.1.2
- lxml==4.9.3
- mat4py==0.5.0
- matplotlib==3.9.2
- matplotlib-inline==0.1.6
- matplotlib-venn==1.1.1
- more-itertools==9.1.0
- msgpack==1.0.4
- nest-asyncio==1.5.5
- numba==0.57.1
- numpy==1.24.4
- openpyxl==3.0.10
- packaging==21.3
- pandas==2.1.4
- parso==0.8.3
- patool==1.12
- patsy==0.5.2
- pexpect==4.8.0
- pickleshare==0.7.5
- Pillow==9.2.0
- platformdirs==3.1.0
- prompt-toolkit==3.0.31
- psutil==5.9.2
- ptyprocess==0.7.0
- pure-eval==0.2.2
- pycparser==2.21
- Pygments==2.13.0
- pymatreader==0.0.30
- pyparsing==3.0.9
- pyproject-toml==0.0.10
- pyrsistent==0.18.1
- python-dateutil==2.8.2
- python-gitlab==3.13.0
- pytz==2022.2.1
- PyYAML==6.0.2
- pyzmq==24.0.1
- requests==2.28.2
- requests-toolbelt==0.10.1
- scikit-learn==1.4.2
- scikit-rvm @ https://github.com/JamesRitchie/scikit-rvm/archive/master.zip
- scipy==1.9.1
- seaborn==0.13.2
- SecretStorage==3.3.3
- six==1.16.0
- sklearn==0.0
- slicer==0.0.7
- stack-data==0.5.0
- statannot==0.2.3
- statsmodels==0.13.2
- style==1.1.0
- tabulate==0.9.0
- termplotlib==0.3.9
- threadpoolctl==3.1.0
- toml==0.10.2
- tornado==6.2
- tqdm==4.65.0
- traitlets==5.4.0
- tzdata==2024.2
- update==0.0.1
- urllib3==1.26.14
- wcwidth==0.2.5
- xmltodict==0.13.0
- zipp==3.15.0
name: QC_env

